language: python
python: "3.4"
cache: apt

os: linux
dist: trusty
sudo: required

addons:
  apt:
    packages:
      - libllvm3.6
      - llvm-runtime
      - clang-3.6

install: pip install pytest-cov python-coveralls
script:
  py.test --cov=compiler --cov-report term-missing
after_script: coveralls
